### ISSUE TITLE
The "from" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [ol-loginov/parcel-namer-rewrite#1]
# 🐛 bug report

When starting Parcel 2 with plugin [parcel-namer-rewrite](https://github.com/ol-loginov/parcel-namer-rewrite) connected to the project building, an error occurs: `parcel-namer-rewrite: The "from" argument must be of type string. Received undefined`

How to resolve this build error?

```bash
yarn build
```
```bash
$ parcel build templates/layouts/index.pug --dist-dir ./build
🚨 Build failed.
parcel-namer-rewrite: The "from" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.relative (path.js:1053:5)
    at nameFromContent (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/namer-default/lib/DefaultNamer.js:140:49)
    at Object.name (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/namer-default/lib/DefaultNamer.js:117:16)
    at Object.name (/Users/andrew/Sites/main-site/src/client/node_modules/parcel-namer-rewrite/lib/Namer.js:32:47)
    at BundlerRunner.nameBundle (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/lib/BundlerRunner.js:181:39)
    at /Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/lib/BundlerRunner.js:169:50
    at Array.map (<anonymous>)
    at BundlerRunner.nameBundles (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/lib/BundlerRunner.js:169:31)
    at async BundlerRunner.bundle (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/lib/BundlerRunner.js:134:5)
parcel-namer-rewrite: Rewrite styles.HASHREFb72dc01010dd39338f4bc3b150ae71dd.css -> styles.css
parcel-namer-rewrite: Rewrite styles.HASHREFc3920eb8ad6d86c5bb3b08894fe854c3.css -> styles.css
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MacBook-Pro-Andrey:client andrew$
```

### package.json
```json
{
    "name": "main-site",
    "engines": {
        "node": "14"
    },
    "isLibrary": false,
    "targets": {
        "legacy": {
            "engines": {
                "browsers": [
                    ">= 0.25%",
                    "maintained node versions"
                ]
            },
            "isLibrary": false,
            "minify": false
        },
        "modern": {
            "engines": {
                "browsers": [
                    "defaults",
                    "not IE 11",
                    "maintained node versions"
                ]
            },
            "isLibrary": false,
            "minify": false
        }
    },
    "parcel-namer-rewrite": {
        "rules": {
            "styles(.*).css": "styles.css"
        }
    },
    "scripts": {
        "serve": "parcel serve templates/layouts/index.pug",
        "build": "parcel build templates/layouts/index.pug --dist-dir ./build"
    }
}
```

### .parcelrc
```json
{
	"extends": "@parcel/config-default",
	"namers": [ "parcel-namer-rewrite" ]
}
```

## 🤔 Expected Behavior

The build should pass successfully without errors and crashes.
Files `build/legacy/styles{~hash}.css` and `build/modern/styles{~hash}.css` should have the output without hash in the names

As we can see the files started to be renamed as expected, but the build folder was never created due to a build error
```bash
parcel-namer-rewrite: Rewrite styles.HASHREFb72dc01010dd39338f4bc3b150ae71dd.css -> styles.css
parcel-namer-rewrite: Rewrite styles.HASHREFc3920eb8ad6d86c5bb3b08894fe854c3.css -> styles.css
```

## 😯 Current Behavior

Due to a build error with the connected [parcel-namer-rewrite](https://github.com/ol-loginov/parcel-namer-rewrite) plugin - the distribution folders `build/legacy/` and `build/modern/` with the point-renamed files `styles.css` without hashes in the names was never created

## 🔦 Context

In my case, after Parcel 2 has build the assets, the builded ready-to-use bundles should work in the WordPress engine, which mainly needs static paths to the sources, that is why the hash should not be present in the bundle name.

For example: instead of a point to WordPress a file named
❌ `build/legacy/styles.a621ca41.css`
we should point
✅ `build/legacy/styles.css`

### index.pug
```pug
block index
    doctype html
    html(lang='en')
        head
        meta(charset='UTF-8')
        meta(name='viewport' content='width=device-width initial-scale=1.0')
        meta(http-equiv='X-UA-Compatible' content='ie=edge')
        title Main Site

        link(rel='stylesheet' href='../../assets/styles/index.scss')

        body
            | Lorem, ipsum dolor.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.1
| Node             |v14.15.3
| npm/Yarn         |6.14.9/1.19.0
| Operating System |macOS Catalina 10.15.7

###### **Note:** _The code above has been truncated to make it more informative, compact, and easier to read. This means that such fields as `devDependencies` are removed._

**Comment by ol-loginov** [comment]
I've created an example to reproduce the issue, but it's still working

Could you please look, if I miss something important in example:
https://github.com/ol-loginov/parcel-namer-rewrite-issues/tree/1

**Comment by ol-loginov** [comment]
And still - thanks for great report
