### ISSUE TITLE
How to remove hash

### ISSUE THREAD

**Issue by jordan-keen** [ol-loginov/parcel-namer-rewrite#14]
Hi there, I just have a question on how I can remove the hash entirely, I added the .parcelrc file and also added the below code in the package.json

`"parcel-namer-rewrite": {
      "hashing": "never"
},`

Should this prevent the has being added or is there another step required, thank you

**Comment by ol-loginov** [comment]
That should do it, `"hashing": "never"` is enough to remove hashes completely

**Comment by ol-loginov** [comment]
I've created minimal example for this issue - https://github.com/ol-loginov/parcel-namer-rewrite-issues/tree/14
In that setup hashing is never happen. If your remove `"hashing": "never"` from package.json there - hashes apper.

Yes, this plugin is not for parcel v1, so this shouldn't work with parcel-bundler 1.12.3.

**Comment by jordan-keen** [comment]
Thanks again for your help! - Looks like we will have to update to Parcel 2
