### ISSUE TITLE
[Suggestion] Join forces with 'structurize' and 'custom-dist-structure'

### ISSUE THREAD

**Issue by iocouto** [ol-loginov/parcel-namer-rewrite#4]
It may be worthwhile getting in touch with a couple of other developers that are trying to develop Parcel plugins to solve the same problem as 'parcel-namer-rewrite'. Perhaps you could all join forces and put together a single 'custom-dist-dir' plugin - which might make the job of maintaining and upgrading the plugin easier for you all. 

There are a couple of projects I know of which are similar to 'parcel-namer-rewrite', and which seem to be actively maintained:

- [parcel-plugin-custom-dist-structure](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure)
- [parcel-plugin-structurize](https://github.com/samrith-s/parcel-plugin-structurize)

**Comment by ol-loginov** [comment]
Thanks for idea, but I think it's too complicated from my point of view.
They are too tighted to the parcel, and therefore should be actively maintened, as parcel does.

I like how parcel goes, and want to see what happens next.
My idea was just change some names, without world domination. 

Anyway, my code is open, anyone can take/change or break it without my permission )

**Comment by Jako** [comment]
You can use this example configuration: https://github.com/ol-loginov/parcel-namer-rewrite/issues/6#issue-992916247 to structure the dist folder.

**Comment by sdavids** [comment]
I created am issue upstream: https://github.com/parcel-bundler/parcel/issues/7573
