### ISSUE TITLE
Following setup instructions in docs, Parcel cannot find 'default' namer

### ISSUE THREAD

**Issue by iocouto** [ol-loginov/parcel-namer-rewrite#5]
I have setup 'parcel-namer-rewrite' exactly as described in the docs here:

1. Brand new project, nothing installed, except the latest version of Parcel, and 'parcel-namer-rewrite'. 
2. Add `.parcelrc` with the exact contents from the instructions here
3. Add `parcel-namer-rewrite` key to my `package.json`, with the following contents:

```json
"parcel-namer-rewrite": {
    "chain": "@parcel/namer-default",
    "rules": {
      "(.*).css": "assets/css/$1{.hash}.css",
      "(.*).js": "assets/js/$1{.hash}.js",
      "(.*).(jpg|png|gif|svg|webp|avif)": "assets/img/$1{.hash}.$2"
    }
  }
```

4. Try to do a build to a custom directory, `/build`, with `parcel build --dist-dir build`. The build fails, with the following error:

```
> parcel build --dist-dir build

🚨 Build failed.

parcel-namer-rewrite: Package 'undefined' has been found, but it's not a namer. 
Set package.json#parcel-namer-rewrite:chain to set a delegate namer ("@parcel/namer-default" by default)
```

I have tried, without any luck:

a. removing the `chain` key from `package.json`
b. adding `"..."` to the end of the list of `namers:` in `.parcelrc`, as [recommended in the docs](https://v2.parceljs.org/configuration/plugin-configuration/#namers)

No luck. Still fails with the same message, every time. 🤷

**Comment by ol-loginov** [comment]
Version https://www.npmjs.com/package/parcel-namer-rewrite/v/2.0.0-rc.0 should fix it

**Comment by ol-loginov** [comment]
Test case https://github.com/ol-loginov/parcel-namer-rewrite-issues/tree/5
