### ISSUE TITLE
Ability to disable the plugin in development mode

### ISSUE THREAD

**Issue by andre-krueger** [ol-loginov/parcel-namer-rewrite#8]
I'm having trouble with this config while serving a html file.

```  
"parcel-namer-rewrite": {
    "rules": {
      "(.*)\\.(js)": "js/$1.{hash}.$2",
      "(.*)\\.(html)": "../../backend/src/templates/$1.$2"
    },
    "silent": true
},
```

After some time, the dev server returns 403  and it can only be fixed by removing the html rule. I'm guessing that the dev server somehow loses access to the file after a rewrite?

I personally don't need the rewriting while in development mode, as I only want the assets to be transferred in production mode, because I need them with the hashed filenames for my backend project.

So it would be good to have a flag to disable the plugin in development mode.

**Comment by ol-loginov** [comment]
https://github.com/ol-loginov/parcel-namer-rewrite#disable-in-development-mode

**Comment by ol-loginov** [comment]
version 2.0.0-rc.2
